# Generated by Django 5.2.4 on 2026-03-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_quotation_executive_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaltask',
            name='rollover_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
