# Generated by Django 5.2.4 on 2026-03-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_internaltask_rollover_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('agent', 'Agent'), ('sales', 'Sales'), ('developer', 'Developer')], default='agent', max_length=50),
        ),
    ]
