# Generated by Django 5.2.16 on 2026-07-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lost_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
