# Generated by Django 5.2.16 on 2026-08-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_lead_age_lead_place_lead_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='collect_demographics',
            field=models.BooleanField(default=True),
        ),
    ]
